name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  clippy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
    - uses: actions/checkout@v3
    
    - name: Cache Cargo build
    - uses: actions/cache@v3
      with:
        path: ~/target
        
    - name: Check project formatting
      run: cargo clippy
